name = "Nyan Cat"
version = 1
author = "Deribus, M3RT1N"
description = "Reproduces the 'Nyan Cat' seasonal event used by the 1st aprils fools prank of 2024. Only compatible with FAForever."
uid = "nyan-cat-01"
icon = "/mods/fa-mod-nyan-cat/icon.png"
copyright = "MIT"
url = "https://github.com/FAForever/fa-mod-nyan-cat"
icon = "/mods/fa-mod-nyan-cat/icon.png"
selectable = true
enabled = true
exclusive = false
ui_only = false
conflicts = { }