name = "W I D E ACUs"
version = 1
author = "Deribus"
description = "Reproduces the 'wide ACU' seasonal event used by the 1st aprils fools prank of 2024. Only compatible with FAForever."
uid = "wide-acu-01"
icon = "/mods/fa-mod-wide-acu/icon.png"
selectable = true
enabled = true
exclusive = false
ui_only = false
conflicts = { }